package umu.tds.maven.apps.PhotoApp.controlador;

public enum Codes {
<<<<<<< HEAD
	INVALID_EMAIL, INVALID_USERNAME, OK, INCORRECT_EMAIL_USERNAME,
	INCORRECT_PASSWORD, ALREADY_LOGGED, NUM_OF_PHOTOS_IN_ALBUM_EXCEEDED
=======
	INVALID_EMAIL, INVALID_USERNAME, OK, INCORRECT_EMAIL_USERNAME, INCORRECT_PASSWORD, ALREADY_LOGGED,
	NUM_OF_PHOTOS_IN_ALBUM_EXCEEDED
>>>>>>> branch 'main' of https://github.com/adriandelrioruiz/PhotoApp.git
}
